### ISSUE TITLE
Overview and Documentation

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#100]
For the governance templates workspace can we make sure that:

- Name is: Postman Open Technologies - Governance Templates
- Overview is informative and describes the workspace and how to get involved and used.
- Each API has a summary and description that describes value so it is searchable via the Postman network.

**Comment by MatthewReinbold** [comment]
Updated - https://www.postman.com/postman/workspace/postman-open-technologies-openapi-governance-templates/overview
