### ISSUE TITLE
Templates Story

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#102]
[Once the workspace and collections are ready for prime time, let's publish a blog post about the workspace, the value it contains, and the role it plays in API governance](https://www.postman.com/postman/workspace/postman-open-technologies-openapi-governance-templates/overview). Showcasing the four areas of templates currently available.

- Information
- Versioning
- Pagination
- Caching
- ISO Standards

This should be a regular occurring blog post, I'd say every quarter, with a round-up of the templates from different relevant categories. Providing ongoing SEO storytelling around this area.

**Comment by MatthewReinbold** [comment]
Blog post here: 
https://docs.google.com/document/d/10V51JpJGyRlkAKuLKlbo38s4z-S_-F5BwH5JpiyzpBQ/edit?usp=sharing

**Comment by kinlane** [comment]
Go ahead and submit to Linda for publishing to the Postman blog -- I will take the content and incorporate it into blueprints.

**Comment by MatthewReinbold** [comment]
submitted to Linda on 12/17

**Comment by MatthewReinbold** [comment]
In the editorial queue here: https://postmanlabs.atlassian.net/browse/BE-115

**Comment by kinlane** [comment]
Here is the blog post - https://blog.postman.com/improve-api-governance-with-shareable-openapi-templates/
