### ISSUE TITLE
Add RFC 8594 (Sunset Header) as Template

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#107]
We need an [OpenAPI template](https://www.postman.com/postman/workspace/openapi-description-templates-for-governance/overview) for RFC 8594 -- response header, component property.

**Comment by MatthewReinbold** [comment]
https://www.postman.com/postman/workspace/postman-open-technologies-openapi-governance-templates/api/7b69ec1f-f71a-48f7-96fd-b314ae238641
