### ISSUE TITLE
Design Guide

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#60]
Add an element for the design guide and add to the higher-level API governance.

**Comment by kinlane** [comment]
We need a high-level overview of what an API design guide is, what it is for, and what the common elements are for an organizational-wide API design guide. 

Let's write as a blog post @MatthewReinbold, and post the draft to Google Doc to edit and move forward as post, but then also post a copy here so we can use the content and elements here for a blueprint.

**Comment by MatthewReinbold** [comment]
Blog post here: https://docs.google.com/document/d/1mrdlqbLIju2QdxYvkwMPF2Ufe73KFU4omAJV4TsKLdI/edit?usp=sharing
