### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#81]
We need a high-level overview of what a design review is, with the elements, roles, and other moving parts of a design review listed.  Let's craft this as a blog post @MatthewReinbold and submit it as a Google doc for review by editorial, then also post here so we can use the content within the [existing blueprint](https://apis.how/blueprints/design-review/) to make it better.

**Comment by MatthewReinbold** [comment]
Blog post on design review:
https://docs.google.com/document/d/17zpy-bIw9fiK6JEmsxZB-BgTT3cHkAOGD6Vx_QLAZuU/edit?usp=sharing

I'll also submit to Linda.

**Comment by MatthewReinbold** [comment]
adding the 'blogs' tag, in addition to queuedContent
