### ISSUE TITLE
Multi-Factor and SSO

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#85]
Let's create some support materials to support Postman customer needs around multi-factor authorization and SSO. Producing the following:

- Answer - Answer the question around "Does Postman Support MFA?"
- Element - SSO - Just a paragraph about what is SSO.
- Element - MFA - Just a paragraph about what is MFA.
- Blog Post - Using Your SSO to Ensure Postman Users Are Using MFA

If we can get an answer in place @MatthewReinbold, and the blog post, then we can better support the customer org and sales.

**Comment by MatthewReinbold** [comment]
Answer: https://apis.how/answers/does-postman-support-mfa/
Elements: https://apis.how/elements/mfa/ and https://apis.how/elements/sso/
Blog Post: https://docs.google.com/document/d/1VgoNM4hVm4YZgQWXVzBnsGsmnIRkPnbvFAxe8JcS1Ws/edit?usp=sharing
