### ISSUE TITLE
Add ISO 8601 (Date) as Template

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#97]
We need [an OpenAPI template](https://www.postman.com/postman/workspace/openapi-description-templates-for-governance/overview) for ISO 8601.

**Comment by kinlane** [comment]
Nice to have as query parameter and schema property.

**Comment by MatthewReinbold** [comment]
Example here:

https://www.postman.com/postman/workspace/postman-open-technologies-openapi-governance-templates/api/eb32d2f8-f6c9-472f-868d-62b7f0e8005c/version/a9f4a852-f0fb-4e16-9bba-3726813294ee
