### ISSUE TITLE
Add ISO 3166 (Country) as Template

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/lifecycle#99]
We need an [OpenAPI template](https://www.postman.com/postman/workspace/openapi-description-templates-for-governance/overview) for ISO 3166 -- query parameters and schema property.

**Comment by MatthewReinbold** [comment]
https://www.postman.com/postman/workspace/postman-open-technologies-openapi-governance-templates/api/eb32d2f8-f6c9-472f-868d-62b7f0e8005c/version/6b5e3e3f-8f14-4fac-9d19-607fe590b6dd
